// src/App.jsx
import React from "react";
import * as Components from "./lib.js";

function App() {
  return (
    <div className="App">
      <h1>All Lib Components</h1>
      <a href="./storybook">Go Stroybook</a>
      {Object.values(Components).map((Component) => {
        return (
          <div>
            <h1>213</h1>
            <img src={require("./examples/assets/code-brackets.svg")} alt="" />
            <Component />
          </div>
        );
      })}
    </div>
  );
}

export default App;

// src/App.vue
<template>
  <div id="app">
    <img alt="Vue logo" src="./examples/assets/colors.svg" />
    <Button label="Test" />
  </div>
</template>

<script>
import Button from "./examples/Button.vue";
export default {
  name: "App",
  components: {
    Button
  }
};
</script>

<style>
/* @import "./index.css"; */
</style>
